title: Ganaka Chandrakumara
description: Ganaka's personal website

#url: https://long-haul.netlify.app
url: https://ganakac.github.io/
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact
    - title: CV
      url: /Resume - Ganaka Chandrakumara.pdf

social:
    #github: brianmaierjr
    #twitter: brianmaierjr
    #facebook: brianmaierjr
    email: ganaka.c@gmail.com
    linkedin: ganaka-chandrakumara
    youtube: ganaka.c
    #tumblr: i-am-a-fish

#google_analytics: "UA-58263416-1"

disqus:
    shortname: ganakac
