title: Ganaka <br> Chandrakumara
description: Ganaka's personal website

#url: https://long-haul.netlify.app
url: https://ganakac.github.io/
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: CV
      url: /Resume.pdf
    - title: Career Highlights
      url: /achievements
    - title: Articles
      url: /articles
    - title: Leisure
      url: /social-media
    #- title: About
     # url: /about
    - title: Connect
      url: /connect

social:
    #github: brianmaierjr
    #twitter: brianmaierjr
    #facebook: brianmaierjr
    email: ganaka.c@gmail.com
    linkedin: ganaka-chandrakumara
    youtube: ganaka.c
    #tumblr: i-am-a-fish

#google_analytics: "UA-58263416-1"  - This is the original line

google_analytics: "G-CHZPPR9LY0"

disqus:
    shortname: ganakac
